---
title: "R Notebook"
output: html_notebook
---

```{r}
required_packages <- c('tidyverse', 'janitor', 'ggthemes',
                       'openintro', 'ggrepel', 'ggpubr', 'scales')

for(p in required_packages){
  if(!require(p,character.only = TRUE))
      install.packages(p, repos = "http://cran.us.r-project.org")
  library(p,character.only = TRUE)
}

base_plot_theme <- function() {
  theme_tufte() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
        axis.text = element_text(face="bold"),
        axis.title.y = element_text(angle = 0, vjust = 0.5),
        axis.ticks = element_blank())
  }
```

# Bar chart

```{r}
mpg %>%
  tabyl(manufacturer) %>%
  ggplot(aes(x=reorder(manufacturer, -percent),
             y=percent)) +
  geom_col(fill="dodgerblue", alpha=0.8) +
  geom_text(aes(label=paste0("n=",n)), vjust=-0.5, size=2) +
  base_plot_theme() +
  scale_y_continuous(labels = scales::percent_format(accuracy=1),
                     breaks = seq(0,1,.02),
                     expand = expansion(mult = c(0, .1))) +
  labs(title="Distribution of Cars of by Manufacturer",
       y="Percent of\nTotal",
       x="Manufacturer")
```

# Stacked Bar Chart
- with layer labels

```{r}
ames_stacked <- ames %>%
  clean_names() %>%
  mutate(neighborhood_grouped = fct_lump_n(neighborhood,n=9)) %>%
  group_by(neighborhood_grouped, house_style) %>%
  count() %>%
  group_by(neighborhood_grouped) %>%
  mutate(pct_total_neighborhood = n/sum(n)) %>%
  ungroup()
  
### orders the plot sequence of how the neighborhoods and house style appear
ames_stacked <- ames_stacked %>%
  group_by(neighborhood_grouped) %>%
  mutate(one_story_nh_pct_total = max(
    ifelse(house_style=="One_Story",pct_total_neighborhood,NA),
    na.rm = T
   )
  ) %>%
  ungroup() %>%
  mutate(neighborhood_grouped = fct_reorder(
    neighborhood_grouped, 
    one_story_nh_pct_total 
   )
  ) %>%
  ungroup() %>%
  mutate(house_style = fct_reorder2(
    house_style, 
    neighborhood_grouped, 
    pct_total_neighborhood
   )
  )

ames_stacked %>%
  ### only label if stack pct total greater than 4%
  mutate(stack_label = case_when(
    pct_total_neighborhood > .04 ~ scales::percent(pct_total_neighborhood,2)
  )) %>%
  ggplot(aes(x=neighborhood_grouped,
             y=pct_total_neighborhood,
             fill=house_style)) +
  geom_col(position = "stack", alpha=0.75) +
  geom_text(aes(label = stack_label),
            position = position_stack(vjust = 0.5),
            size=3) +
  base_plot_theme() +
  theme(legend.title = element_text(size = 8), 
        legend.text = element_text(size = 8),
        axis.text.y = element_blank()) +
  labs(title="Ames, IA: House Style Sold\n2006 to 2010 by Neighborhood Group",
    x="Neighborhood Group",
    y="Percent\nof Total",
    fill="House Style")
```

# Histogram
```{r}
### ggpubr for out of the box histograms with ease
```

# Density Plot
```{r}
### ggpubr for out of the box density charts
```

# Scatter Plot

```{r}
states_scatter <- us_rent_income %>%
  select(NAME, variable, estimate) %>%
  pivot_wider(names_from=variable, values_from=estimate) %>%
  mutate(state_abb = usdata::state2abbr(NAME)) %>%
  filter(NAME!="Puerto Rico") ### drop PR | no income data

states_scatter %>%
  ggplot(aes(x=rent, y=income)) + 
  geom_smooth(method="lm") +
  stat_cor(p.accuracy = 0.001, r.accuracy = 0.01, cor.coef.name="r") +
  geom_text_repel(aes(label=state_abb), 
                  box.padding=0.01,
                  size=2.5,
                  font.face="bold") +
  scale_x_continuous(labels=dollar_format()) +
  scale_y_continuous(labels=dollar_format()) +
  base_plot_theme() +
  labs(title = "US State\nMedian Yearly Income vs Median Monthly Rent",
       x="Median Monthly Rent",
       y="Median \nYearly \nIncome ",
       caption = "r = pearson correlation coefficient")
```

# Boxplot
- compare US region median income 
- use above states data and pull in region var

# Faceted with Grid

# Faceted with Wrap

# Labels on trend lines end points

# Dumbbell Plot

```{r}
library(directlabels)
mpg_mm <- mpg %>%
  group_by(year, manufacturer) %>%
  count() %>%
  group_by(year) %>%
  mutate(pct_total = n/sum(n)) %>%
  ungroup()

db_plot <- mpg_mm %>%
  ggplot(aes(x=factor(year),
             y=pct_total,
             color=manufacturer,
             group=manufacturer)) +
  geom_line(alpha=0.7, size=1.5) +
  geom_point() +
  scale_y_continuous(labels = scales::percent_format(accuracy=1),
                   breaks = seq(0,1,.02)) +
  scale_x_discrete(expand = expansion(mult = c(0.05, 6))) +
  base_plot_theme() +
  theme(axis.title.x = element_text(hjust = 0, margin = margin(t=6))) +
  labs(title = "1999 vs 2008",
       subtitle="Manufacturer Percent Total Change",
       x="Year",
       y="Percent of\nTotal")

direct.label(db_plot,  list(dl.trans(x=x+0.25), cex=0.5, "last.qp"))
```

